//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofek.Invoice4U_LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonObject", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.PrintOpetions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.DocumentCsv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.DocumentItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.Discount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.ClientCsv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_LoginService.User))]
    public partial class CommonObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_LoginService.CommonError[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_LoginService.CommonError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintOpetions", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class PrintOpetions : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AllowedPaymentMethodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BankDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CodeCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscountTypeCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrawingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EarlyPaymentDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasFixedLatePaymentPenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemDiscountCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatePaymentTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RoundAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AllowedPaymentMethods {
            get {
                return this.AllowedPaymentMethodsField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedPaymentMethodsField, value) != true)) {
                    this.AllowedPaymentMethodsField = value;
                    this.RaisePropertyChanged("AllowedPaymentMethods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BankDetails {
            get {
                return this.BankDetailsField;
            }
            set {
                if ((this.BankDetailsField.Equals(value) != true)) {
                    this.BankDetailsField = value;
                    this.RaisePropertyChanged("BankDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CodeCullom {
            get {
                return this.CodeCullomField;
            }
            set {
                if ((this.CodeCullomField.Equals(value) != true)) {
                    this.CodeCullomField = value;
                    this.RaisePropertyChanged("CodeCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiscountTypeCullom {
            get {
                return this.DiscountTypeCullomField;
            }
            set {
                if ((this.DiscountTypeCullomField.Equals(value) != true)) {
                    this.DiscountTypeCullomField = value;
                    this.RaisePropertyChanged("DiscountTypeCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentTemplate {
            get {
                return this.DocumentTemplateField;
            }
            set {
                if ((this.DocumentTemplateField.Equals(value) != true)) {
                    this.DocumentTemplateField = value;
                    this.RaisePropertyChanged("DocumentTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drawing {
            get {
                return this.DrawingField;
            }
            set {
                if ((object.ReferenceEquals(this.DrawingField, value) != true)) {
                    this.DrawingField = value;
                    this.RaisePropertyChanged("Drawing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EarlyPaymentDiscount {
            get {
                return this.EarlyPaymentDiscountField;
            }
            set {
                if ((this.EarlyPaymentDiscountField.Equals(value) != true)) {
                    this.EarlyPaymentDiscountField = value;
                    this.RaisePropertyChanged("EarlyPaymentDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasFixedLatePaymentPenalty {
            get {
                return this.HasFixedLatePaymentPenaltyField;
            }
            set {
                if ((this.HasFixedLatePaymentPenaltyField.Equals(value) != true)) {
                    this.HasFixedLatePaymentPenaltyField = value;
                    this.RaisePropertyChanged("HasFixedLatePaymentPenalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HtmlText {
            get {
                return this.HtmlTextField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlTextField, value) != true)) {
                    this.HtmlTextField = value;
                    this.RaisePropertyChanged("HtmlText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ItemDiscountCullom {
            get {
                return this.ItemDiscountCullomField;
            }
            set {
                if ((this.ItemDiscountCullomField.Equals(value) != true)) {
                    this.ItemDiscountCullomField = value;
                    this.RaisePropertyChanged("ItemDiscountCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LatePaymentTax {
            get {
                return this.LatePaymentTaxField;
            }
            set {
                if ((this.LatePaymentTaxField.Equals(value) != true)) {
                    this.LatePaymentTaxField = value;
                    this.RaisePropertyChanged("LatePaymentTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote1 {
            get {
                return this.LegalNote1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote1Field, value) != true)) {
                    this.LegalNote1Field = value;
                    this.RaisePropertyChanged("LegalNote1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote2 {
            get {
                return this.LegalNote2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote2Field, value) != true)) {
                    this.LegalNote2Field = value;
                    this.RaisePropertyChanged("LegalNote2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote3 {
            get {
                return this.LegalNote3Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote3Field, value) != true)) {
                    this.LegalNote3Field = value;
                    this.RaisePropertyChanged("LegalNote3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote4 {
            get {
                return this.LegalNote4Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote4Field, value) != true)) {
                    this.LegalNote4Field = value;
                    this.RaisePropertyChanged("LegalNote4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RoundAmount {
            get {
                return this.RoundAmountField;
            }
            set {
                if ((this.RoundAmountField.Equals(value) != true)) {
                    this.RoundAmountField = value;
                    this.RaisePropertyChanged("RoundAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateColor {
            get {
                return this.TemplateColorField;
            }
            set {
                if ((this.TemplateColorField.Equals(value) != true)) {
                    this.TemplateColorField = value;
                    this.RaisePropertyChanged("TemplateColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentCsv", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class DocumentCsv : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChargeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DocumentCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_LoginService.DocumentItem[] DocumentItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExerciseSecurityCertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FirstPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGeneralClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OtherPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessFullClearingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TaxRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthNumber {
            get {
                return this.AuthNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthNumberField, value) != true)) {
                    this.AuthNumberField = value;
                    this.RaisePropertyChanged("AuthNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargeType {
            get {
                return this.ChargeTypeField;
            }
            set {
                if ((this.ChargeTypeField.Equals(value) != true)) {
                    this.ChargeTypeField = value;
                    this.RaisePropertyChanged("ChargeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditNumber {
            get {
                return this.CreditNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditNumberField, value) != true)) {
                    this.CreditNumberField = value;
                    this.RaisePropertyChanged("CreditNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DocumentCreated {
            get {
                return this.DocumentCreatedField;
            }
            set {
                if ((this.DocumentCreatedField.Equals(value) != true)) {
                    this.DocumentCreatedField = value;
                    this.RaisePropertyChanged("DocumentCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_LoginService.DocumentItem[] DocumentItems {
            get {
                return this.DocumentItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentItemsField, value) != true)) {
                    this.DocumentItemsField = value;
                    this.RaisePropertyChanged("DocumentItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExerciseSecurityCertificate {
            get {
                return this.ExerciseSecurityCertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExerciseSecurityCertificateField, value) != true)) {
                    this.ExerciseSecurityCertificateField = value;
                    this.RaisePropertyChanged("ExerciseSecurityCertificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FirstPayment {
            get {
                return this.FirstPaymentField;
            }
            set {
                if ((this.FirstPaymentField.Equals(value) != true)) {
                    this.FirstPaymentField = value;
                    this.RaisePropertyChanged("FirstPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGeneralClient {
            get {
                return this.IsGeneralClientField;
            }
            set {
                if ((this.IsGeneralClientField.Equals(value) != true)) {
                    this.IsGeneralClientField = value;
                    this.RaisePropertyChanged("IsGeneralClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo {
            get {
                return this.MailToField;
            }
            set {
                if ((object.ReferenceEquals(this.MailToField, value) != true)) {
                    this.MailToField = value;
                    this.RaisePropertyChanged("MailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPayments {
            get {
                return this.NumOfPaymentsField;
            }
            set {
                if ((this.NumOfPaymentsField.Equals(value) != true)) {
                    this.NumOfPaymentsField = value;
                    this.RaisePropertyChanged("NumOfPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OtherPayments {
            get {
                return this.OtherPaymentsField;
            }
            set {
                if ((this.OtherPaymentsField.Equals(value) != true)) {
                    this.OtherPaymentsField = value;
                    this.RaisePropertyChanged("OtherPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessFullClearing {
            get {
                return this.SuccessFullClearingField;
            }
            set {
                if ((this.SuccessFullClearingField.Equals(value) != true)) {
                    this.SuccessFullClearingField = value;
                    this.RaisePropertyChanged("SuccessFullClearing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxRate {
            get {
                return this.TaxRateField;
            }
            set {
                if ((this.TaxRateField.Equals(value) != true)) {
                    this.TaxRateField = value;
                    this.RaisePropertyChanged("TaxRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentItem", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class DocumentItem : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AvrageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ConversionRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_LoginService.Discount DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TaxPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalWithoutTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCatalogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCategoryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Avrage {
            get {
                return this.AvrageField;
            }
            set {
                if ((this.AvrageField.Equals(value) != true)) {
                    this.AvrageField = value;
                    this.RaisePropertyChanged("Avrage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ConversionRate {
            get {
                return this.ConversionRateField;
            }
            set {
                if ((this.ConversionRateField.Equals(value) != true)) {
                    this.ConversionRateField = value;
                    this.RaisePropertyChanged("ConversionRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_LoginService.Discount Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TaxPercentage {
            get {
                return this.TaxPercentageField;
            }
            set {
                if ((this.TaxPercentageField.Equals(value) != true)) {
                    this.TaxPercentageField = value;
                    this.RaisePropertyChanged("TaxPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalWithoutTax {
            get {
                return this.TotalWithoutTaxField;
            }
            set {
                if ((this.TotalWithoutTaxField.Equals(value) != true)) {
                    this.TotalWithoutTaxField = value;
                    this.RaisePropertyChanged("TotalWithoutTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCatalogID {
            get {
                return this.UserCatalogIDField;
            }
            set {
                if ((this.UserCatalogIDField.Equals(value) != true)) {
                    this.UserCatalogIDField = value;
                    this.RaisePropertyChanged("UserCatalogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCategoryID {
            get {
                return this.UserCategoryIDField;
            }
            set {
                if ((this.UserCategoryIDField.Equals(value) != true)) {
                    this.UserCategoryIDField = value;
                    this.RaisePropertyChanged("UserCategoryID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Discount", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class Discount : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BeforeTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNominalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BeforeTax {
            get {
                return this.BeforeTaxField;
            }
            set {
                if ((this.BeforeTaxField.Equals(value) != true)) {
                    this.BeforeTaxField = value;
                    this.RaisePropertyChanged("BeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNominal {
            get {
                return this.IsNominalField;
            }
            set {
                if ((this.IsNominalField.Equals(value) != true)) {
                    this.IsNominalField = value;
                    this.RaisePropertyChanged("IsNominal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientCsv", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class ClientCsv : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BussinesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtrnalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BussinesNumber {
            get {
                return this.BussinesNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BussinesNumberField, value) != true)) {
                    this.BussinesNumberField = value;
                    this.RaisePropertyChanged("BussinesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtrnalNumber {
            get {
                return this.ExtrnalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtrnalNumberField, value) != true)) {
                    this.ExtrnalNumberField = value;
                    this.RaisePropertyChanged("ExtrnalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((this.PaymentsField.Equals(value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class User : Ofek.Invoice4U_LoginService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountingMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ForeverClosePopupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAdminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutomaicInvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthlyClosePopupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthlyClosePopupUnPressedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OldInvoiceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrganizationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SMSCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowOldInvoiceLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TaxRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Ucan2ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserLanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ViewDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountingMethod {
            get {
                return this.AccountingMethodField;
            }
            set {
                if ((this.AccountingMethodField.Equals(value) != true)) {
                    this.AccountingMethodField = value;
                    this.RaisePropertyChanged("AccountingMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaCode {
            get {
                return this.AreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaCodeField, value) != true)) {
                    this.AreaCodeField = value;
                    this.RaisePropertyChanged("AreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType {
            get {
                return this.BusinessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTypeField, value) != true)) {
                    this.BusinessTypeField = value;
                    this.RaisePropertyChanged("BusinessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ForeverClosePopup {
            get {
                return this.ForeverClosePopupField;
            }
            set {
                if ((this.ForeverClosePopupField.Equals(value) != true)) {
                    this.ForeverClosePopupField = value;
                    this.RaisePropertyChanged("ForeverClosePopup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin {
            get {
                return this.IsAdminField;
            }
            set {
                if ((this.IsAdminField.Equals(value) != true)) {
                    this.IsAdminField = value;
                    this.RaisePropertyChanged("IsAdmin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutomaicInvoices {
            get {
                return this.IsAutomaicInvoicesField;
            }
            set {
                if ((this.IsAutomaicInvoicesField.Equals(value) != true)) {
                    this.IsAutomaicInvoicesField = value;
                    this.RaisePropertyChanged("IsAutomaicInvoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthlyClosePopup {
            get {
                return this.MonthlyClosePopupField;
            }
            set {
                if ((this.MonthlyClosePopupField.Equals(value) != true)) {
                    this.MonthlyClosePopupField = value;
                    this.RaisePropertyChanged("MonthlyClosePopup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthlyClosePopupUnPressed {
            get {
                return this.MonthlyClosePopupUnPressedField;
            }
            set {
                if ((this.MonthlyClosePopupUnPressedField.Equals(value) != true)) {
                    this.MonthlyClosePopupUnPressedField = value;
                    this.RaisePropertyChanged("MonthlyClosePopupUnPressed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OldInvoiceID {
            get {
                return this.OldInvoiceIDField;
            }
            set {
                if ((this.OldInvoiceIDField.Equals(value) != true)) {
                    this.OldInvoiceIDField = value;
                    this.RaisePropertyChanged("OldInvoiceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationCurrency {
            get {
                return this.OrganizationCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationCurrencyField, value) != true)) {
                    this.OrganizationCurrencyField = value;
                    this.RaisePropertyChanged("OrganizationCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrganizationID {
            get {
                return this.OrganizationIDField;
            }
            set {
                if ((this.OrganizationIDField.Equals(value) != true)) {
                    this.OrganizationIDField = value;
                    this.RaisePropertyChanged("OrganizationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SMSCode {
            get {
                return this.SMSCodeField;
            }
            set {
                if ((this.SMSCodeField.Equals(value) != true)) {
                    this.SMSCodeField = value;
                    this.RaisePropertyChanged("SMSCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowOldInvoiceLink {
            get {
                return this.ShowOldInvoiceLinkField;
            }
            set {
                if ((this.ShowOldInvoiceLinkField.Equals(value) != true)) {
                    this.ShowOldInvoiceLinkField = value;
                    this.RaisePropertyChanged("ShowOldInvoiceLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxRate {
            get {
                return this.TaxRateField;
            }
            set {
                if ((this.TaxRateField.Equals(value) != true)) {
                    this.TaxRateField = value;
                    this.RaisePropertyChanged("TaxRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ucan2Active {
            get {
                return this.Ucan2ActiveField;
            }
            set {
                if ((this.Ucan2ActiveField.Equals(value) != true)) {
                    this.Ucan2ActiveField = value;
                    this.RaisePropertyChanged("Ucan2Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserLanguage {
            get {
                return this.UserLanguageField;
            }
            set {
                if ((this.UserLanguageField.Equals(value) != true)) {
                    this.UserLanguageField = value;
                    this.RaisePropertyChanged("UserLanguage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ViewDate {
            get {
                return this.ViewDateField;
            }
            set {
                if ((this.ViewDateField.Equals(value) != true)) {
                    this.ViewDateField = value;
                    this.RaisePropertyChanged("ViewDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonError", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class CommonError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamtersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paramters {
            get {
                return this.ParamtersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamtersField, value) != true)) {
                    this.ParamtersField = value;
                    this.RaisePropertyChanged("Paramters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Invoice", ConfigurationName="Invoice4U_LoginService.LoginService")]
    public interface LoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/LoginService/VerifyLogin", ReplyAction="Invoice/LoginService/VerifyLoginResponse")]
        string VerifyLogin(string username, string password, bool isPersistent);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/LoginService/IsAuthenticated", ReplyAction="Invoice/LoginService/IsAuthenticatedResponse")]
        Ofek.Invoice4U_LoginService.User IsAuthenticated(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/LoginService/Logout", ReplyAction="Invoice/LoginService/LogoutResponse")]
        void Logout();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceChannel : Ofek.Invoice4U_LoginService.LoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<Ofek.Invoice4U_LoginService.LoginService>, Ofek.Invoice4U_LoginService.LoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string VerifyLogin(string username, string password, bool isPersistent) {
            return base.Channel.VerifyLogin(username, password, isPersistent);
        }
        
        public Ofek.Invoice4U_LoginService.User IsAuthenticated(string token) {
            return base.Channel.IsAuthenticated(token);
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
    }
}
