//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofek.Invoice4U_CustomerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonObject", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.PrintOpetions))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.DocumentCsv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.DocumentItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.Discount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.ClientCsv))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.PaymentDetailes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.CommonCollectionOfArrayOfCustomerJHiVxprS))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Ofek.Invoice4U_CustomerService.Customer))]
    public partial class CommonObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_CustomerService.CommonError[] ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_CustomerService.CommonError[] Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PrintOpetions", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class PrintOpetions : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] AllowedPaymentMethodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BankDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CodeCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DiscountTypeCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentTemplateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DrawingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EarlyPaymentDiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasFixedLatePaymentPenaltyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemDiscountCullomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> LatePaymentTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LegalNote4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RoundAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TemplateColorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] AllowedPaymentMethods {
            get {
                return this.AllowedPaymentMethodsField;
            }
            set {
                if ((object.ReferenceEquals(this.AllowedPaymentMethodsField, value) != true)) {
                    this.AllowedPaymentMethodsField = value;
                    this.RaisePropertyChanged("AllowedPaymentMethods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BankDetails {
            get {
                return this.BankDetailsField;
            }
            set {
                if ((this.BankDetailsField.Equals(value) != true)) {
                    this.BankDetailsField = value;
                    this.RaisePropertyChanged("BankDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CodeCullom {
            get {
                return this.CodeCullomField;
            }
            set {
                if ((this.CodeCullomField.Equals(value) != true)) {
                    this.CodeCullomField = value;
                    this.RaisePropertyChanged("CodeCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DiscountTypeCullom {
            get {
                return this.DiscountTypeCullomField;
            }
            set {
                if ((this.DiscountTypeCullomField.Equals(value) != true)) {
                    this.DiscountTypeCullomField = value;
                    this.RaisePropertyChanged("DiscountTypeCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentTemplate {
            get {
                return this.DocumentTemplateField;
            }
            set {
                if ((this.DocumentTemplateField.Equals(value) != true)) {
                    this.DocumentTemplateField = value;
                    this.RaisePropertyChanged("DocumentTemplate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Drawing {
            get {
                return this.DrawingField;
            }
            set {
                if ((object.ReferenceEquals(this.DrawingField, value) != true)) {
                    this.DrawingField = value;
                    this.RaisePropertyChanged("Drawing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EarlyPaymentDiscount {
            get {
                return this.EarlyPaymentDiscountField;
            }
            set {
                if ((this.EarlyPaymentDiscountField.Equals(value) != true)) {
                    this.EarlyPaymentDiscountField = value;
                    this.RaisePropertyChanged("EarlyPaymentDiscount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasFixedLatePaymentPenalty {
            get {
                return this.HasFixedLatePaymentPenaltyField;
            }
            set {
                if ((this.HasFixedLatePaymentPenaltyField.Equals(value) != true)) {
                    this.HasFixedLatePaymentPenaltyField = value;
                    this.RaisePropertyChanged("HasFixedLatePaymentPenalty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HtmlText {
            get {
                return this.HtmlTextField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlTextField, value) != true)) {
                    this.HtmlTextField = value;
                    this.RaisePropertyChanged("HtmlText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ItemDiscountCullom {
            get {
                return this.ItemDiscountCullomField;
            }
            set {
                if ((this.ItemDiscountCullomField.Equals(value) != true)) {
                    this.ItemDiscountCullomField = value;
                    this.RaisePropertyChanged("ItemDiscountCullom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> LatePaymentTax {
            get {
                return this.LatePaymentTaxField;
            }
            set {
                if ((this.LatePaymentTaxField.Equals(value) != true)) {
                    this.LatePaymentTaxField = value;
                    this.RaisePropertyChanged("LatePaymentTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote1 {
            get {
                return this.LegalNote1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote1Field, value) != true)) {
                    this.LegalNote1Field = value;
                    this.RaisePropertyChanged("LegalNote1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote2 {
            get {
                return this.LegalNote2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote2Field, value) != true)) {
                    this.LegalNote2Field = value;
                    this.RaisePropertyChanged("LegalNote2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote3 {
            get {
                return this.LegalNote3Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote3Field, value) != true)) {
                    this.LegalNote3Field = value;
                    this.RaisePropertyChanged("LegalNote3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LegalNote4 {
            get {
                return this.LegalNote4Field;
            }
            set {
                if ((object.ReferenceEquals(this.LegalNote4Field, value) != true)) {
                    this.LegalNote4Field = value;
                    this.RaisePropertyChanged("LegalNote4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RoundAmount {
            get {
                return this.RoundAmountField;
            }
            set {
                if ((this.RoundAmountField.Equals(value) != true)) {
                    this.RoundAmountField = value;
                    this.RaisePropertyChanged("RoundAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TemplateColor {
            get {
                return this.TemplateColorField;
            }
            set {
                if ((this.TemplateColorField.Equals(value) != true)) {
                    this.TemplateColorField = value;
                    this.RaisePropertyChanged("TemplateColor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentCsv", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class DocumentCsv : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CVVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChargeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreditNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DocumentCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_CustomerService.DocumentItem[] DocumentItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExerciseSecurityCertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FirstPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsGeneralClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumOfPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double OtherPaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessFullClearingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TaxRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthNumber {
            get {
                return this.AuthNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthNumberField, value) != true)) {
                    this.AuthNumberField = value;
                    this.RaisePropertyChanged("AuthNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CVV {
            get {
                return this.CVVField;
            }
            set {
                if ((object.ReferenceEquals(this.CVVField, value) != true)) {
                    this.CVVField = value;
                    this.RaisePropertyChanged("CVV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChargeType {
            get {
                return this.ChargeTypeField;
            }
            set {
                if ((this.ChargeTypeField.Equals(value) != true)) {
                    this.ChargeTypeField = value;
                    this.RaisePropertyChanged("ChargeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreditNumber {
            get {
                return this.CreditNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CreditNumberField, value) != true)) {
                    this.CreditNumberField = value;
                    this.RaisePropertyChanged("CreditNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DocumentCreated {
            get {
                return this.DocumentCreatedField;
            }
            set {
                if ((this.DocumentCreatedField.Equals(value) != true)) {
                    this.DocumentCreatedField = value;
                    this.RaisePropertyChanged("DocumentCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_CustomerService.DocumentItem[] DocumentItems {
            get {
                return this.DocumentItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentItemsField, value) != true)) {
                    this.DocumentItemsField = value;
                    this.RaisePropertyChanged("DocumentItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExerciseSecurityCertificate {
            get {
                return this.ExerciseSecurityCertificateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExerciseSecurityCertificateField, value) != true)) {
                    this.ExerciseSecurityCertificateField = value;
                    this.RaisePropertyChanged("ExerciseSecurityCertificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpiryDate {
            get {
                return this.ExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpiryDateField, value) != true)) {
                    this.ExpiryDateField = value;
                    this.RaisePropertyChanged("ExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FirstPayment {
            get {
                return this.FirstPaymentField;
            }
            set {
                if ((this.FirstPaymentField.Equals(value) != true)) {
                    this.FirstPaymentField = value;
                    this.RaisePropertyChanged("FirstPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNumberField, value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGeneralClient {
            get {
                return this.IsGeneralClientField;
            }
            set {
                if ((this.IsGeneralClientField.Equals(value) != true)) {
                    this.IsGeneralClientField = value;
                    this.RaisePropertyChanged("IsGeneralClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailTo {
            get {
                return this.MailToField;
            }
            set {
                if ((object.ReferenceEquals(this.MailToField, value) != true)) {
                    this.MailToField = value;
                    this.RaisePropertyChanged("MailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumOfPayments {
            get {
                return this.NumOfPaymentsField;
            }
            set {
                if ((this.NumOfPaymentsField.Equals(value) != true)) {
                    this.NumOfPaymentsField = value;
                    this.RaisePropertyChanged("NumOfPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double OtherPayments {
            get {
                return this.OtherPaymentsField;
            }
            set {
                if ((this.OtherPaymentsField.Equals(value) != true)) {
                    this.OtherPaymentsField = value;
                    this.RaisePropertyChanged("OtherPayments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SuccessFullClearing {
            get {
                return this.SuccessFullClearingField;
            }
            set {
                if ((this.SuccessFullClearingField.Equals(value) != true)) {
                    this.SuccessFullClearingField = value;
                    this.RaisePropertyChanged("SuccessFullClearing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TaxRate {
            get {
                return this.TaxRateField;
            }
            set {
                if ((this.TaxRateField.Equals(value) != true)) {
                    this.TaxRateField = value;
                    this.RaisePropertyChanged("TaxRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentItem", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class DocumentItem : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AvrageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ConversionRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_CustomerService.Discount DiscountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> TaxPercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TotalWithoutTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCatalogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCategoryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Avrage {
            get {
                return this.AvrageField;
            }
            set {
                if ((this.AvrageField.Equals(value) != true)) {
                    this.AvrageField = value;
                    this.RaisePropertyChanged("Avrage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ConversionRate {
            get {
                return this.ConversionRateField;
            }
            set {
                if ((this.ConversionRateField.Equals(value) != true)) {
                    this.ConversionRateField = value;
                    this.RaisePropertyChanged("ConversionRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_CustomerService.Discount Discount {
            get {
                return this.DiscountField;
            }
            set {
                if ((object.ReferenceEquals(this.DiscountField, value) != true)) {
                    this.DiscountField = value;
                    this.RaisePropertyChanged("Discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> TaxPercentage {
            get {
                return this.TaxPercentageField;
            }
            set {
                if ((this.TaxPercentageField.Equals(value) != true)) {
                    this.TaxPercentageField = value;
                    this.RaisePropertyChanged("TaxPercentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalTax {
            get {
                return this.TotalTaxField;
            }
            set {
                if ((this.TotalTaxField.Equals(value) != true)) {
                    this.TotalTaxField = value;
                    this.RaisePropertyChanged("TotalTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double TotalWithoutTax {
            get {
                return this.TotalWithoutTaxField;
            }
            set {
                if ((this.TotalWithoutTaxField.Equals(value) != true)) {
                    this.TotalWithoutTaxField = value;
                    this.RaisePropertyChanged("TotalWithoutTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCatalogID {
            get {
                return this.UserCatalogIDField;
            }
            set {
                if ((this.UserCatalogIDField.Equals(value) != true)) {
                    this.UserCatalogIDField = value;
                    this.RaisePropertyChanged("UserCatalogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserCategoryID {
            get {
                return this.UserCategoryIDField;
            }
            set {
                if ((this.UserCategoryIDField.Equals(value) != true)) {
                    this.UserCategoryIDField = value;
                    this.RaisePropertyChanged("UserCategoryID");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Discount", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class Discount : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BeforeTaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsNominalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BeforeTax {
            get {
                return this.BeforeTaxField;
            }
            set {
                if ((this.BeforeTaxField.Equals(value) != true)) {
                    this.BeforeTaxField = value;
                    this.RaisePropertyChanged("BeforeTax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsNominal {
            get {
                return this.IsNominalField;
            }
            set {
                if ((this.IsNominalField.Equals(value) != true)) {
                    this.IsNominalField = value;
                    this.RaisePropertyChanged("IsNominal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientCsv", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class ClientCsv : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BussinesNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtrnalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BussinesNumber {
            get {
                return this.BussinesNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BussinesNumberField, value) != true)) {
                    this.BussinesNumberField = value;
                    this.RaisePropertyChanged("BussinesNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtrnalNumber {
            get {
                return this.ExtrnalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtrnalNumberField, value) != true)) {
                    this.ExtrnalNumberField = value;
                    this.RaisePropertyChanged("ExtrnalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Payments {
            get {
                return this.PaymentsField;
            }
            set {
                if ((this.PaymentsField.Equals(value) != true)) {
                    this.PaymentsField = value;
                    this.RaisePropertyChanged("Payments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDetailes", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class PaymentDetailes : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClientIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountOwner {
            get {
                return this.AccountOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountOwnerField, value) != true)) {
                    this.AccountOwnerField = value;
                    this.RaisePropertyChanged("AccountOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BIC {
            get {
                return this.BICField;
            }
            set {
                if ((object.ReferenceEquals(this.BICField, value) != true)) {
                    this.BICField = value;
                    this.RaisePropertyChanged("BIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonCollectionOfArrayOfCustomerJHiVxprS", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class CommonCollectionOfArrayOfCustomerJHiVxprS : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ofek.Invoice4U_CustomerService.Customer[] ResponseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ofek.Invoice4U_CustomerService.Customer[] Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class Customer : Ofek.Invoice4U_CustomerService.CommonObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ExtNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedIdnentifer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedIdnentifer2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedIdnentifer3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtendedIdnentifer4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double FreeBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeUniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FrenchBusinessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> HasBeenExportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsAutomaicInvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrgIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PayTermsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RetainerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RetainerAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RetainerTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Ucan2ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniqueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebsiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Capital {
            get {
                return this.CapitalField;
            }
            set {
                if ((this.CapitalField.Equals(value) != true)) {
                    this.CapitalField = value;
                    this.RaisePropertyChanged("Capital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cell {
            get {
                return this.CellField;
            }
            set {
                if ((object.ReferenceEquals(this.CellField, value) != true)) {
                    this.CellField = value;
                    this.RaisePropertyChanged("Cell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactFirstName {
            get {
                return this.ContactFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactFirstNameField, value) != true)) {
                    this.ContactFirstNameField = value;
                    this.RaisePropertyChanged("ContactFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactLastName {
            get {
                return this.ContactLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactLastNameField, value) != true)) {
                    this.ContactLastNameField = value;
                    this.RaisePropertyChanged("ContactLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ExtNumber {
            get {
                return this.ExtNumberField;
            }
            set {
                if ((this.ExtNumberField.Equals(value) != true)) {
                    this.ExtNumberField = value;
                    this.RaisePropertyChanged("ExtNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedIdnentifer1 {
            get {
                return this.ExtendedIdnentifer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedIdnentifer1Field, value) != true)) {
                    this.ExtendedIdnentifer1Field = value;
                    this.RaisePropertyChanged("ExtendedIdnentifer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedIdnentifer2 {
            get {
                return this.ExtendedIdnentifer2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedIdnentifer2Field, value) != true)) {
                    this.ExtendedIdnentifer2Field = value;
                    this.RaisePropertyChanged("ExtendedIdnentifer2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedIdnentifer3 {
            get {
                return this.ExtendedIdnentifer3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedIdnentifer3Field, value) != true)) {
                    this.ExtendedIdnentifer3Field = value;
                    this.RaisePropertyChanged("ExtendedIdnentifer3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtendedIdnentifer4 {
            get {
                return this.ExtendedIdnentifer4Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedIdnentifer4Field, value) != true)) {
                    this.ExtendedIdnentifer4Field = value;
                    this.RaisePropertyChanged("ExtendedIdnentifer4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FreeBalance {
            get {
                return this.FreeBalanceField;
            }
            set {
                if ((this.FreeBalanceField.Equals(value) != true)) {
                    this.FreeBalanceField = value;
                    this.RaisePropertyChanged("FreeBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreeUniqueID {
            get {
                return this.FreeUniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeUniqueIDField, value) != true)) {
                    this.FreeUniqueIDField = value;
                    this.RaisePropertyChanged("FreeUniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreeZip {
            get {
                return this.FreeZipField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeZipField, value) != true)) {
                    this.FreeZipField = value;
                    this.RaisePropertyChanged("FreeZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FrenchBusinessType {
            get {
                return this.FrenchBusinessTypeField;
            }
            set {
                if ((this.FrenchBusinessTypeField.Equals(value) != true)) {
                    this.FrenchBusinessTypeField = value;
                    this.RaisePropertyChanged("FrenchBusinessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid {
            get {
                return this.GuidField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidField, value) != true)) {
                    this.GuidField = value;
                    this.RaisePropertyChanged("Guid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> HasBeenExported {
            get {
                return this.HasBeenExportedField;
            }
            set {
                if ((this.HasBeenExportedField.Equals(value) != true)) {
                    this.HasBeenExportedField = value;
                    this.RaisePropertyChanged("HasBeenExported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsAutomaicInvoices {
            get {
                return this.IsAutomaicInvoicesField;
            }
            set {
                if ((this.IsAutomaicInvoicesField.Equals(value) != true)) {
                    this.IsAutomaicInvoicesField = value;
                    this.RaisePropertyChanged("IsAutomaicInvoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((this.OrgIDField.Equals(value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PayTerms {
            get {
                return this.PayTermsField;
            }
            set {
                if ((this.PayTermsField.Equals(value) != true)) {
                    this.PayTermsField = value;
                    this.RaisePropertyChanged("PayTerms");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Retainer {
            get {
                return this.RetainerField;
            }
            set {
                if ((this.RetainerField.Equals(value) != true)) {
                    this.RetainerField = value;
                    this.RaisePropertyChanged("Retainer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> RetainerAmount {
            get {
                return this.RetainerAmountField;
            }
            set {
                if ((this.RetainerAmountField.Equals(value) != true)) {
                    this.RetainerAmountField = value;
                    this.RaisePropertyChanged("RetainerAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetainerTitle {
            get {
                return this.RetainerTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.RetainerTitleField, value) != true)) {
                    this.RetainerTitleField = value;
                    this.RaisePropertyChanged("RetainerTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Ucan2ClientID {
            get {
                return this.Ucan2ClientIDField;
            }
            set {
                if ((this.Ucan2ClientIDField.Equals(value) != true)) {
                    this.Ucan2ClientIDField = value;
                    this.RaisePropertyChanged("Ucan2ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UniqueIDField, value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonError", Namespace="http://schemas.datacontract.org/2004/07/Invoice.Common")]
    [System.SerializableAttribute()]
    public partial class CommonError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParamtersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paramters {
            get {
                return this.ParamtersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParamtersField, value) != true)) {
                    this.ParamtersField = value;
                    this.RaisePropertyChanged("Paramters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Invoice", ConfigurationName="Invoice4U_CustomerService.CustomerService")]
    public interface CustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/Create", ReplyAction="Invoice/CustomerService/CreateResponse")]
        Ofek.Invoice4U_CustomerService.Customer Create(Ofek.Invoice4U_CustomerService.Customer customer, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/Get", ReplyAction="Invoice/CustomerService/GetResponse")]
        Ofek.Invoice4U_CustomerService.Customer Get(int id, int orgID, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/GetClientsPaymentDetailes", ReplyAction="Invoice/CustomerService/GetClientsPaymentDetailesResponse")]
        Ofek.Invoice4U_CustomerService.PaymentDetailes GetClientsPaymentDetailes(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/Autocomplete", ReplyAction="Invoice/CustomerService/AutocompleteResponse")]
        Ofek.Invoice4U_CustomerService.Customer[] Autocomplete(string q, int limit, bool onlyActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/AutocompleteMobile", ReplyAction="Invoice/CustomerService/AutocompleteMobileResponse")]
        Ofek.Invoice4U_CustomerService.Customer[] AutocompleteMobile(string q, int limit, bool onlyActive, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/GetCustomers", ReplyAction="Invoice/CustomerService/GetCustomersResponse")]
        Ofek.Invoice4U_CustomerService.CommonCollectionOfArrayOfCustomerJHiVxprS GetCustomers(Ofek.Invoice4U_CustomerService.Customer cust, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/UpdateExternalNumber", ReplyAction="Invoice/CustomerService/UpdateExternalNumberResponse")]
        Ofek.Invoice4U_CustomerService.CommonCollectionOfArrayOfCustomerJHiVxprS UpdateExternalNumber(Ofek.Invoice4U_CustomerService.Customer[] cust);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/GetByName", ReplyAction="Invoice/CustomerService/GetByNameResponse")]
        Ofek.Invoice4U_CustomerService.Customer GetByName(string name, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/Delete", ReplyAction="Invoice/CustomerService/DeleteResponse")]
        Ofek.Invoice4U_CustomerService.CommonObject Delete(Ofek.Invoice4U_CustomerService.Customer[] customers);
        
        [System.ServiceModel.OperationContractAttribute(Action="Invoice/CustomerService/GetByGuid", ReplyAction="Invoice/CustomerService/GetByGuidResponse")]
        Ofek.Invoice4U_CustomerService.Customer GetByGuid(string guid, string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceChannel : Ofek.Invoice4U_CustomerService.CustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Ofek.Invoice4U_CustomerService.CustomerService>, Ofek.Invoice4U_CustomerService.CustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ofek.Invoice4U_CustomerService.Customer Create(Ofek.Invoice4U_CustomerService.Customer customer, string token) {
            return base.Channel.Create(customer, token);
        }
        
        public Ofek.Invoice4U_CustomerService.Customer Get(int id, int orgID, string token) {
            return base.Channel.Get(id, orgID, token);
        }
        
        public Ofek.Invoice4U_CustomerService.PaymentDetailes GetClientsPaymentDetailes(int clientId) {
            return base.Channel.GetClientsPaymentDetailes(clientId);
        }
        
        public Ofek.Invoice4U_CustomerService.Customer[] Autocomplete(string q, int limit, bool onlyActive) {
            return base.Channel.Autocomplete(q, limit, onlyActive);
        }
        
        public Ofek.Invoice4U_CustomerService.Customer[] AutocompleteMobile(string q, int limit, bool onlyActive, string token) {
            return base.Channel.AutocompleteMobile(q, limit, onlyActive, token);
        }
        
        public Ofek.Invoice4U_CustomerService.CommonCollectionOfArrayOfCustomerJHiVxprS GetCustomers(Ofek.Invoice4U_CustomerService.Customer cust, string token) {
            return base.Channel.GetCustomers(cust, token);
        }
        
        public Ofek.Invoice4U_CustomerService.CommonCollectionOfArrayOfCustomerJHiVxprS UpdateExternalNumber(Ofek.Invoice4U_CustomerService.Customer[] cust) {
            return base.Channel.UpdateExternalNumber(cust);
        }
        
        public Ofek.Invoice4U_CustomerService.Customer GetByName(string name, string token) {
            return base.Channel.GetByName(name, token);
        }
        
        public Ofek.Invoice4U_CustomerService.CommonObject Delete(Ofek.Invoice4U_CustomerService.Customer[] customers) {
            return base.Channel.Delete(customers);
        }
        
        public Ofek.Invoice4U_CustomerService.Customer GetByGuid(string guid, string token) {
            return base.Channel.GetByGuid(guid, token);
        }
    }
}
