//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofek.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://account.invoice4u.co.il/Public/w_invoicereceipt.asmx")]
        public string Ofek_Invoice4U_InvoiceReceipt_w_invoicereceipt {
            get {
                return ((string)(this["Ofek_Invoice4U_InvoiceReceipt_w_invoicereceipt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://account.invoice4u.co.il/Public/w_invoice.asmx")]
        public string Ofek_Invoice4U_Invoice_w_invoice {
            get {
                return ((string)(this["Ofek_Invoice4U_Invoice_w_invoice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://account.invoice4u.co.il/Public/w_receipt.asmx")]
        public string Ofek_Invoice4U_Receipt_w_receipt {
            get {
                return ((string)(this["Ofek_Invoice4U_Receipt_w_receipt"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://account.invoice4u.co.il/Public/w_company.asmx")]
        public string Ofek_Invoice4U_Company_w_company {
            get {
                return ((string)(this["Ofek_Invoice4U_Company_w_company"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.zcredit.co.il/ZCreditWS.asmx")]
        public string Ofek_ZCreditWS_clsZCreditWS {
            get {
                return ((string)(this["Ofek_ZCreditWS_clsZCreditWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://account.invoice4u.co.il/Public/w_invoicedeal.asmx")]
        public string Ofek_Invoice4U_InvoiceDeal_w_invoicedeal {
            get {
                return ((string)(this["Ofek_Invoice4U_InvoiceDeal_w_invoicedeal"]));
            }
        }
    }
}
